/*
 * Analog support routines.
 *
 * @author Michel Megens
 * @email  michel@michelmegens.net
 */

#include <sam.h>
#include <hal_gpio.h>

#include <lwiot/samd51/adcchip.h>

void analog_set_reference(AnalogReference mode)
{
	while(ADC0->SYNCBUSY.reg & ADC_SYNCBUSY_REFCTRL);
	while(ADC1->SYNCBUSY.reg & ADC_SYNCBUSY_REFCTRL);

	switch (mode) {
	case AR_INTERNAL1V0:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_1V0_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_INTERNAL1V1:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_1V1_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_INTERNAL1V2:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_1V2_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_INTERNAL1V25:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_1V25_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_INTERNAL2V0:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_2V0_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_INTERNAL2V2:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_2V2_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_INTERNAL2V4:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_2V4_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_INTERNAL2V5:
		SUPC->VREF.bit.SEL = SUPC_VREF_SEL_2V5_Val;
		SUPC->VREF.bit.VREFOE = 1;
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTREF_Val;
		break;

	case AR_EXTERNAL:
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_AREFA_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_AREFA_Val;
		break;

	case AR_INTERNAL1V65:
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTVCC0_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTVCC0_Val;
		break;

	case AR_DEFAULT:
	default:
		ADC0->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTVCC1_Val;
		ADC1->REFCTRL.bit.REFSEL = ADC_REFCTRL_REFSEL_INTVCC1_Val;
		break;
	}
}

uint8_t adc0_pin_map[] = {
	GPIO(GPIO_PORTA, 2),
	GPIO(GPIO_PORTA, 3),
	GPIO(GPIO_PORTB, 8),
	GPIO(GPIO_PORTB, 9),
	GPIO(GPIO_PORTA, 4),
	GPIO(GPIO_PORTA, 5),
	GPIO(GPIO_PORTA, 6),
	GPIO(GPIO_PORTA, 7),
	GPIO(GPIO_PORTA, 8),
	GPIO(GPIO_PORTA, 9),
	GPIO(GPIO_PORTA, 10),
	GPIO(GPIO_PORTA, 11),
	GPIO(GPIO_PORTB, 0),
	GPIO(GPIO_PORTB, 1),
	GPIO(GPIO_PORTB, 2),
	GPIO(GPIO_PORTB, 15),
};

uint8_t adc1_pin_map[] = {
	GPIO(GPIO_PORTB, 8), // AIN0
	GPIO(GPIO_PORTB, 9), // AIN1
	GPIO(GPIO_PORTA, 8), // AIN2
	GPIO(GPIO_PORTA, 9), // AIN3
	GPIO(GPIO_PORTC, 2), // AIN4
	GPIO(GPIO_PORTC, 3), // AIN5
	GPIO(GPIO_PORTB, 4), // AIN6
	GPIO(GPIO_PORTB, 5), // AIN7
	GPIO(GPIO_PORTB, 6), // AIN8
	GPIO(GPIO_PORTA, 7), // AIN9
	GPIO(GPIO_PORTC, 0), // AIN10
	GPIO(GPIO_PORTC, 1), // AIN11
	GPIO(GPIO_PORTC, 30), // AIN12
	GPIO(GPIO_PORTC, 31), // AIN13
	GPIO(GPIO_PORTD, 0), // AIN14
	GPIO(GPIO_PORTD, 1) // AIN15
};
